class Beeper extends Sugar implements Runnable
{
    private int beep = 0;
    private String name = null;
    public Beeper(String name, int beep)
    {
        this.name = name;
        this.beep = beep;
        System.out.println(name + " is alive, beep=" + beep);
    }
    public void run()
    {
        long value = 1;
        System.out.println("age()=" + age() + ", "
                           + name + " running");
// so main() thread has priority and
// surely gets CPU later to interrupt() us
        Thread.currentThread().setPriority(
            Thread.currentThread().getPriority()-1);
        while (true)
        {
            if (value++ % beep == 0)
            {
                System.out.println("age()=" + age()
                                   + ", " + name + " beeps, value=" + value);
                if (Thread.interrupted())
                {
                    System.out.println("age=" + age() + ", "
                                       + name + " interrupted");
                    return;
                }
            }
        }
    }
}
class Beeping extends Sugar
{
    public static void main(String[] args)
    {
        int numBeepers = 4;
        int beep = 100000;
        String timeSlice = "no";
        int runTime = 60; // default in seconds
        try
        {
            numBeepers = Integer.parseInt(args[0]);
            beep = Integer.parseInt(args[1]);
            timeSlice = args[2];
            runTime = Integer.parseInt(args[3]);
        }
        catch (Exception e) { /* use defaults */ }
        System.out.println("Beeping: numBeepers=" + numBeepers
                           + ", beep=" + beep + ", timeSlice=" + timeSlice
                           + ", runTime=" + runTime);
        if (timeSlice.equals("yes"))
// for Solaris, not Windows 95/NT
            new PseudoTimeSlicing();
// start the Beeper threads
        Thread[] b = new Thread[numBeepers];
        for (int i = 0; i < numBeepers; i++)
            b[i] = new Thread(new Beeper("Beeper"+i, beep));
        for (int i = 0; i < numBeepers; i++)
            b[i].start();
        System.out.println("All Beeper threads started");
// let the Beepers run for a while
        try
        {
            Thread.sleep(runTime*1000);
            System.out.println("age=" + age()
                               + ", time to interrupt the Beepers and exit");
            for (int i = 0; i < numBeepers; i++)
                b[i].interrupt();
            for (int i = 0; i < numBeepers; i++)
                b[i].join();
        }
        catch (InterruptedException e) { /* ignored */ }
        System.out.println("All Beeper threads interrupted");
        System.exit(0);
    }
}

/*
% javac beep.java
% java Beeping 4 100000 no 3
Beeping:
numBeepers=4, beep=100000, timeSlice=no, runTime=3
                                     Beeper0 is alive, beep=100000
                                             Beeper1 is alive, beep=100000
                                                     Beeper2 is alive, beep=100000
                                                             Beeper3 is alive, beep=100000
                                                                     age()=36, Beeper0 running
                                                                             age()=134, Beeper1 running
                                                                                     age()=195, Beeper2 running
                                                                                             All Beeper threads started
                                                                                             age()=225, Beeper3 running
                                                                                                     age()=374, Beeper3 beeps, value=100001
                                                                                                             age()=600, Beeper2 beeps, value=100001
                                                                                                                     age()=769, Beeper1 beeps, value=100001
                                                                                                                             age()=901, Beeper0 beeps, value=100001
                                                                                                                                     age()=1050, Beeper0 beeps, value=200001
                                                                                                                                             age()=1125, Beeper1 beeps, value=200001
                                                                                                                                                     age()=1287, Beeper3 beeps, value=200001
                                                                                                                                                             age()=1392, Beeper2 beeps, value=200001
                                                                                                                                                                     age()=1671, Beeper1 beeps, value=300001
                                                                                                                                                                             age()=1757, Beeper0 beeps, value=300001
                                                                                                                                                                                     age()=1988, Beeper3 beeps, value=300001
                                                                                                                                                                                             age()=2063, Beeper2 beeps, value=300001
                                                                                                                                                                                                     age()=2209, Beeper2 beeps, value=400001
                                                                                                                                                                                                             age()=2426, Beeper0 beeps, value=400001
                                                                                                                                                                                                                     age()=2499, Beeper1 beeps, value=400001
                                                                                                                                                                                                                             age()=2688, Beeper3 beeps, value=400001
                                                                                                                                                                                                                                     age()=2979, Beeper1 beeps, value=500001
                                                                                                                                                                                                                                             age()=3073, Beeper0 beeps, value=500001
                                                                                                                                                                                                                                                     age()=3219, Beeper0 beeps, value=600001
                                                                                                                                                                                                                                                             age=3234, time to interrupt the Beepers and exit
                                                                                                                                                                                                                                                                     age()=3290, Beeper2 beeps, value=500001
                                                                                                                                                                                                                                                                             age=3291, Beeper2 interrupted
                                                                                                                                                                                                                                                                                     age()=3321, Beeper3 beeps, value=500001
                                                                                                                                                                                                                                                                                             age=3322, Beeper3 interrupted
                                                                                                                                                                                                                                                                                                     age()=3444, Beeper1 beeps, value=600001
                                                                                                                                                                                                                                                                                                             age=3445, Beeper1 interrupted
                                                                                                                                                                                                                                                                                                                     age()=3578, Beeper0 beeps, value=700001
                                                                                                                                                                                                                                                                                                                             age=3578, Beeper0 interrupted
                                                                                                                                                                                                                                                                                                                                     All Beeper threads interrupted
                                                                                                                                                                                                                                                                                                                                     % java Beeping 4 100000 yes 3
                                                                                                                                                                                                                                                                                                                                     Beeping:
                                                                                                                                                                                                                                                                                                                                     numBeepers=4, beep=100000, timeSlice=yes, runTime=3
                                                                                                                                                                                                                                                                                                                                             Java version=1.3.0
                                                                                                                                                                                                                                                                                                                                                     Java vendor=IBM Corporation
                                                                                                                                                                                                                                                                                                                                                             OS name=Linux
                                                                                                                                                                                                                                                                                                                                                                     OS arch=i586
                                                                                                                                                                                                                                                                                                                                                                             OS version=#1 Mon Sep 27 10:25:54 EDT 1999.2.2.12-20
                                                                                                                                                                                                                                                                                                                                                                                     No PseudoTimeSlicing needed
                                                                                                                                                                                                                                                                                                                                                                                     Beeper0 is alive, beep=100000
                                                                                                                                                                                                                                                                                                                                                                                             Beeper1 is alive, beep=100000
                                                                                                                                                                                                                                                                                                                                                                                                     Beeper2 is alive, beep=100000
                                                                                                                                                                                                                                                                                                                                                                                                             Beeper3 is alive, beep=100000
                                                                                                                                                                                                                                                                                                                                                                                                                     age()=38, Beeper0 running
                                                                                                                                                                                                                                                                                                                                                                                                                             age()=168, Beeper1 running
                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=293, Beeper0 beeps, value=100001
                                                                                                                                                                                                                                                                                                                                                                                                                                             age()=439, Beeper0 beeps, value=200001
                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=536, Beeper1 beeps, value=100001
                                                                                                                                                                                                                                                                                                                                                                                                                                                             age()=618, Beeper2 running
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     All Beeper threads started
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=741, Beeper3 running
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             age()=855, Beeper2 beeps, value=100001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=922, Beeper1 beeps, value=200001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             age()=1195, Beeper0 beeps, value=300001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=1319, Beeper3 beeps, value=100001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             age()=1562, Beeper2 beeps, value=200001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=1702, Beeper0 beeps, value=400001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             age()=1977, Beeper2 beeps, value=300001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=2078, Beeper1 beeps, value=300001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             age()=2225, Beeper1 beeps, value=400001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=2266, Beeper3 beeps, value=200001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             age()=2413, Beeper3 beeps, value=300001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=2561, Beeper1 beeps, value=500001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             age()=2740, Beeper2 beeps, value=400001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=2743, Beeper0 beeps, value=500001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             age()=3021, Beeper2 beeps, value=500001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=3124, Beeper0 beeps, value=600001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             age()=3185, Beeper3 beeps, value=400001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=3322, Beeper1 beeps, value=600001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             age()=3672, Beeper0 beeps, value=700001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=3723, Beeper3 beeps, value=500001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             age=3748, time to interrupt the Beepers and exit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=3840, Beeper1 beeps, value=700001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             age=3841, Beeper1 interrupted
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=3906, Beeper2 beeps, value=600001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             age=3906, Beeper2 interrupted
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=4066, Beeper3 beeps, value=600001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             age=4067, Beeper3 interrupted
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     age()=4108, Beeper0 beeps, value=800001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             age=4109, Beeper0 interrupted
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     All Beeper threads interrupted

*/